import test from 'node:test';import assert from 'node:assert/strict';
import {runtime} from '../tools/runtime.mjs';import {createRoom,act} from '../server/game.mjs';
import {simulationTick} from '../server/simulation.mjs';import {worldState,placeBot,moveWorld} from '../server/world.mjs';
import {route,pathPosition,nextDoor} from '../public/navigation.js';import {clearPath,distance,EVIDENCE_SPOTS} from '../public/world-map.js';
import {activityAction,activityView} from '../server/activities.mjs';
import '../tools/build.mjs';
import http from 'node:http';
import {config} from '../server/ai.mjs';
test('autonomous model budget survives a concurrent room update and failed result commit',async()=>{
 let calls=0;const provider=http.createServer(async(req,res)=>{for await(const _ of req){}calls++;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:'{"text":"test reply","vote":null}'}}]}));});await new Promise(r=>provider.listen(0,'127.0.0.1',r));const {mf,db}=await runtime();
 try{const r=createRoom('BUDGET','host','房主');act(r,'host','setBot',{role:1,enabled:true});r.phase=2;r.settings={autonomousNpc:true};await db.prepare('INSERT INTO rooms VALUES(?,?,?,?,?)').bind(r.code,0,JSON.stringify(r),'host',2).run();await db.prepare('INSERT INTO seats VALUES(?,?,?)').bind(r.code,'host',Date.now()).run();await simulationTick(db,r.code);let sim=JSON.parse((await db.prepare('SELECT body FROM simulation').first()).body);sim.at-=2000;sim.npcs[r.players[1].id].due=0;await db.prepare('UPDATE simulation SET body=?').bind(JSON.stringify(sim)).run();
 const cfg=config({DEEPSEEK_API_KEY:'test-only',AI_BASE_URL:'http://127.0.0.1:'+provider.address().port});await simulationTick(db,r.code,{cfg,history:async()=>{const current=JSON.parse((await db.prepare('SELECT body FROM rooms').first()).body);current.revision++;await db.prepare('UPDATE rooms SET body=?,revision=?').bind(JSON.stringify(current),current.revision).run();return [];}});
 const current=JSON.parse((await db.prepare('SELECT body FROM rooms').first()).body);assert.equal(calls,1);assert.equal(current.aiCount,1);assert.equal(current.autoAiCount,1);assert.equal(current.autoAiCalls[r.players[1].id],1);assert.ok(current.autoAiAt>0);
 current.autoAiCount=24;current.autoAiAt=0;await db.prepare('UPDATE rooms SET body=?').bind(JSON.stringify(current)).run();await simulationTick(db,r.code,{cfg,history:async()=>[]});assert.equal(calls,1,'exhausted autonomous budget must not call the provider again');
 }finally{await mf.dispose();provider.closeAllConnections();await new Promise(r=>provider.close(r));}
});
test('path projection never replaces a player identity with a door identifier',()=>{assert.deepEqual(pathPosition([{x:0,y:0},{id:'lounge',to:'lounge',x:1,y:0}],100),{x:1,y:0,arrived:true});});
test('navigation detours around furniture with collision-checked segments and time-based arrival',()=>{const p=route('hall',{x:384,y:368},{x:384,y:96});assert.ok(p.length>2);for(let i=1;i<p.length;i++)assert.ok(clearPath('hall',p[i-1],p[i]));assert.equal(pathPosition(p,0).arrived,false);assert.equal(pathPosition(p,100000).arrived,true);assert.equal(nextDoor('study','bank',3).to,'garden');assert.equal(nextDoor('hall','bank',2),null);});
test('NPC D1 authority: no clue before walking, capped offline progress, pause, concurrent lease',async()=>{
 const {mf,db}=await runtime();try{const r=createRoom('ABCDEF','host','房主');act(r,'host','role',{role:0});act(r,'host','setBot',{role:2,enabled:true});r.settings={autonomousNpc:true,minigamesEnabled:true};r.phase=3;r.players[1].ap=3;const bot=r.players[1];await db.prepare('INSERT INTO rooms(code,revision,body,host,phase) VALUES(?,?,?,?,?)').bind(r.code,0,JSON.stringify(r),'host',3).run();await db.prepare('INSERT INTO seats(room,player,seen) VALUES(?,?,?)').bind(r.code,'host',Date.now()).run();
 await simulationTick(db,r.code);let sim=JSON.parse((await db.prepare('SELECT body FROM simulation').first()).body);sim.npcs[bot.id].due=0;sim.at-=2000;await db.prepare('UPDATE simulation SET body=?').bind(JSON.stringify(sim)).run();await simulationTick(db,r.code);
 let current=JSON.parse((await db.prepare('SELECT body FROM rooms').first()).body);assert.equal(current.players[1].clues.length,0);sim=JSON.parse((await db.prepare('SELECT body FROM simulation').first()).body);assert.equal(sim.npcs[bot.id].status,'walking');const before=sim.npcs[bot.id].position;
 // Simulate a long offline gap: only a bounded tick may advance, never an hour of rewards.
 sim.at-=3600000;sim.npcs[bot.id].started-=3600000;await db.prepare('UPDATE simulation SET body=?').bind(JSON.stringify(sim)).run();await simulationTick(db,r.code);sim=JSON.parse((await db.prepare('SELECT body FROM simulation').first()).body);assert.ok(distance(before,sim.npcs[bot.id].position)<=301);current=JSON.parse((await db.prepare('SELECT body FROM rooms').first()).body);assert.equal(current.players[1].clues.length,0);
 await simulationTick(db,r.code,{actor:'host',command:{type:'pause',playerId:bot.id}});const paused=(await worldState(db,current)).players[1];await Promise.all([simulationTick(db,r.code),simulationTick(db,r.code)]);const after=(await worldState(db,current)).players[1];assert.equal(distance(paused,after),0);assert.equal(after.status,'paused');
 // Advance real route time in small increments, while checking the spatial evidence rule at collection.
 await simulationTick(db,r.code,{actor:'host',command:{type:'resume',playerId:bot.id}});
 for(let i=0;i<40;i++){sim=JSON.parse((await db.prepare('SELECT body FROM simulation').first()).body);sim.at-=2000;for(const n of Object.values(sim.npcs)){n.started-=2000;n.due=0;}await db.prepare('UPDATE simulation SET body=?').bind(JSON.stringify(sim)).run();await simulationTick(db,r.code);current=JSON.parse((await db.prepare('SELECT body FROM rooms').first()).body);if(current.players[1].clues.length){const pos=(await worldState(db,current)).players[1];assert.equal(pos.scene,EVIDENCE_SPOTS['alice-letter'].scene);assert.ok(distance(pos,EVIDENCE_SPOTS['alice-letter'])<=56);break;}}
 assert.equal(current.players[1].clues[0],'alice-letter');
 current.players.push({id:'other',name:'旁人'});await db.prepare('UPDATE rooms SET body=?').bind(JSON.stringify(current)).run();sim=JSON.parse((await db.prepare('SELECT body FROM simulation').first()).body);sim.npcs[bot.id].position={scene:'meeting-a',x:384,y:352,phase:3};sim.npcs[bot.id].path=null;await db.prepare('UPDATE simulation SET body=?').bind(JSON.stringify(sim)).run();await placeBot(db,current,'host','meeting-a',344,352);await placeBot(db,current,'other','hall',48,144);const other=(await worldState(db,current)).players.find(p=>p.id==='other');await assert.rejects(()=>moveWorld(db,current,'other',{type:'door',target:'meeting-a',phase:3,seq:other.seq+1}),/已满/);
 }finally{await mf.dispose();}
});
test('card table D1: spatial entry, two-seat race, private hands, duplicate actions, phase cancellation',async()=>{const {mf,db}=await runtime();try{const r=createRoom('FEDCBA','a','甲');r.players.push({id:'b',name:'乙'},{id:'c',name:'丙'});r.settings={minigamesEnabled:true};await db.prepare('INSERT INTO rooms(code,revision,body,host,phase) VALUES(?,?,?,?,?)').bind(r.code,0,JSON.stringify(r),'a',0).run();for(const id of ['a','b','c']){await db.prepare('INSERT INTO seats VALUES(?,?,?)').bind(r.code,id,Date.now()).run();await placeBot(db,r,id,'lounge',384,304);}const data=(type,extra={})=>({type,requestId:crypto.randomUUID(),...extra});await activityAction(db,r,'a',data('sit'));const race=await Promise.allSettled(['b','c'].map(id=>activityAction(db,r,id,data('sit'))));assert.equal(race.filter(x=>x.status==='fulfilled').length,1);let g=(await activityView(db,r,'a')).game;assert.equal(g.seats.length,2);assert.equal(g.hands[1],null);const fixture=JSON.parse((await db.prepare('SELECT body FROM activities WHERE room=?').bind(r.code).first()).body);fixture.hands=[[1,2],[3,4]];fixture.done=[false,false];fixture.status='playing';fixture.deck=Array.from({length:52},(_,i)=>i).filter(i=>![1,2,3,4].includes(i));await db.prepare('UPDATE activities SET body=? WHERE room=?').bind(JSON.stringify(fixture),r.code).run();const req=data('stand');await activityAction(db,r,'a',req);await activityAction(db,r,'a',req);g=(await activityView(db,r,'a')).game;assert.equal(g.done[0],true);r.phase=1;r.revision++;await db.prepare('UPDATE rooms SET phase=1,revision=?,body=?').bind(r.revision,JSON.stringify(r)).run();await activityAction(db,r,'a',data('tick'));assert.equal((await activityView(db,r,'a')).game.status,'cancelled');}finally{await mf.dispose();}});
