import assert from 'node:assert/strict';import {chromium} from 'playwright';import {runtime} from './runtime.mjs';import {go,walk} from './scene-test-helpers.mjs';import {mkdirSync} from 'node:fs';
const {mf}=await runtime(),origin=(await mf.ready).origin;const browser=await chromium.launch({channel:'chrome',headless:true});const contexts=await Promise.all([0,1].map(()=>browser.newContext({viewport:{width:1440,height:1000}}))),pages=await Promise.all(contexts.map(c=>c.newPage()));const errors=[];mkdirSync('test-results',{recursive:true});
try{for(const [i,p]of pages.entries()){p.on('pageerror',e=>errors.push(e.message));await p.goto(origin);await p.locator('#connection').filter({hasText:'身份已就绪'}).waitFor();await p.locator('#name').fill('牌友'+i);}const [a,b]=pages;await a.locator('#create').click();await a.locator('#roomCode').filter({hasText:/[A-F0-9]{6}/}).waitFor();const code=await a.locator('#roomCode').innerText();await b.locator('#code').fill(code);await b.locator('#joinForm button').click();await b.locator('#world').waitFor();
 for(const p of pages){await go(p,'lounge');await walk(p,{x:384,y:304});await p.keyboard.press('Space');await p.locator('dialog').waitFor();}
 await a.getByRole('button',{name:'坐下，等待朋友',exact:true}).click();await b.getByRole('button',{name:'加入牌局',exact:true}).waitFor();await b.getByRole('button',{name:'加入牌局',exact:true}).click();await a.locator('.card-hand').first().waitFor();assert.equal(await a.locator('.card-hand').first().locator('img[alt="背面"]').count(),2);
 await a.screenshot({path:'test-results/cards-human-desktop.png',fullPage:true});await b.setViewportSize({width:390,height:844});await b.screenshot({path:'test-results/cards-human-mobile.png',fullPage:true});assert.equal(await b.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 for(let round=1;round<=3;round++){for(const p of pages){const stand=p.getByRole('button',{name:'停牌',exact:true});if(await stand.isEnabled().catch(()=>false))await stand.click();}if(round<3)await a.getByRole('heading',{name:new RegExp(`第 ${round+1} / 3`)}).waitFor({timeout:15000});else await a.getByRole('heading',{name:/本场比分/}).waitFor({timeout:15000});}
 await a.getByRole('button',{name:'记忆翻牌',exact:true}).click();const grid=a.locator('.memory-grid');await grid.locator('button').nth(0).click();await grid.locator('button').nth(1).click();await grid.locator('button').nth(2).click();assert.ok(await grid.locator('img:not([alt="背面"])').count()<=3);await a.screenshot({path:'test-results/memory-desktop.png',fullPage:true});
 await a.getByRole('button',{name:'关闭 ×',exact:true}).click();await b.getByRole('button',{name:'关闭 ×',exact:true}).click();await b.screenshot({path:'test-results/lounge-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,humanDuel:true,rounds:3,privateHands:true,memory:true,mobileOverflow:false}));
}catch(e){await pages[0].screenshot({path:'test-results/games-failure.png',fullPage:true});throw e;}finally{await browser.close();await mf.dispose();}
