// Visual fixtures only: gameplay is exercised separately by browser-check and browser-games.
import assert from 'node:assert/strict';import {mkdirSync,writeFileSync} from 'node:fs';import {chromium} from 'playwright';import {runtime} from './runtime.mjs';import {createRoom,join,view} from '../server/game.mjs';import {SCENES} from '../public/world-map.js';
const {mf}=await runtime(),origin=(await mf.ready).origin;const browser=await chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage({viewport:{width:1440,height:1000}});const dir='test-results/polish';mkdirSync(dir,{recursive:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));const shots=[];
async function shot(name){await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' horizontal overflow');await p.screenshot({path:dir+'/'+name+'.png',fullPage:true});shots.push(name);}
const r=createRoom('ABC123','visual-0','林间来客');for(let i=1;i<4;i++)join(r,'visual-'+i,['','詹姆斯','爱丽丝','威廉'][i]);r.settings={autonomousNpc:false};r.players.forEach((q,i)=>{q.role=i;q.ap=3;q.clues=i===0?['turner-pocket','weapon']:[];q.shared=[];q.vote={suspect:0,method:'沿时间线核对证据。',evidence:['weapon']};});let rev=10000;
async function show(phase,scene,panel){r.phase=phase;r.revision=rev++;r.deadline=phase>0&&phase<8?Date.now()+360000:null;r.published=phase>=4?['turner-pocket','weapon']:[];r.messages=[{id:'one',from:'visual-1',to:null,text:'我想再核对一下下午的时间。你们在水潭边看到了什么？',at:Date.now()},{id:'two',from:'visual-2',to:null,text:'先看证据，再听每个人的解释。',at:Date.now()}];const v={...view(r,'visual-0',r.players.map(q=>q.id)),settings:r.settings,activities:{open:[0,4,8].includes(phase),game:null},world:{players:r.players.map((q,i)=>({id:q.id,scene,x:324+i*40,y:368,phase,seq:0}))},signals:[],chatScene:scene,ai:{configured:true,model:'deepseek-flash',remaining:48},hostAbsentSince:null};await p.evaluate(v=>{clearTimeout(reconnect);generation++;state=null;room=v.code;document.querySelector('#entry').hidden=true;document.querySelector('#game').hidden=false;accept(v);},v);await p.waitForFunction(s=>document.querySelector('#world').dataset.scene===s,scene);await p.evaluate(()=>{for(const x of document.querySelectorAll('.tool-panel:not([hidden]) .panel-close'))x.click();});if(panel)await p.locator('[data-panel="'+panel+'"]').click();}
try{await p.goto(origin);await p.locator('#connection').filter({hasText:'身份已就绪'}).waitFor();await p.waitForFunction(()=>document.querySelector('#world').dataset.artReady==='true');await p.evaluate(()=>Promise.all([...document.images].map(i=>i.decode())));await shot('entry-desktop');await p.setViewportSize({width:390,height:844});await shot('entry-mobile');await p.setViewportSize({width:1440,height:1000});await show(0,'hall');await shot('lobby-desktop');for(const scene of Object.keys(SCENES)){await show(scene==='reading'?1:scene==='lounge'?4:3,scene);await shot('scene-'+scene);}
for(const [id,phase,scene]of [['book',1,'reading'],['evidencePanel',4,'hall'],['hostPanel',4,'hall'],['notesPanel',4,'hall'],['votePanel',7,'hall'],['ending',8,'hall']]){await show(phase,scene,id);if(id==='notesPanel')await p.locator('#note').fill('15:05  到达水潭\n15:16  谁还留在现场？\n待核对：脚印、披风、雪茄。');await shot('panel-'+id);await p.setViewportSize({width:390,height:844});await shot('mobile-'+id);await p.setViewportSize({width:1440,height:1000});}
await p.setViewportSize({width:390,height:844});await show(0,'hall');await shot('lobby-mobile');await show(3,'garden');await shot('scene-mobile');await show(4,'meeting-a','discussionPanel');await shot('private-mobile');await p.setViewportSize({width:1440,height:1000});await p.evaluate(()=>document.documentElement.style.fontSize='200%');await show(4,'hall','evidencePanel');await shot('text-enlarged');assert.ok(await p.evaluate(()=>parseFloat(getComputedStyle(document.body).fontSize)>=32),'200% text size applied');assert.deepEqual(errors,[]);writeFileSync(dir+'/report.json',JSON.stringify({passed:true,visualFixtures:true,shots,errors},null,2));console.log(JSON.stringify({passed:true,screenshots:shots.length,errors}));}finally{await browser.close();await mf.dispose();}
